In [ ]:
from google.colab import files
import pandas as pd

In [ ]:
encoding_type = "utf-8-sig"

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/ideaOwl/betacityyeg-dive-opentable/main/data/2020-2021vs2019_Seated_Diner_Data.csv', encoding=encoding_type)

In [ ]:
df_unpivoted = data.melt(id_vars=['Type', 'Name'], var_name='date', value_name='change_from_2019')
df_unpivoted

          Type        Name       date change_from_2019
0      country      Global  2020/2/18              -1%
1      country   Australia  2020/2/18              -3%
2      country      Canada  2020/2/18              -5%
3      country     Germany  2020/2/18              11%
4      country     Ireland  2020/2/18               2%
...        ...         ...        ...              ...
91003     city       Tampa  2022/1/28           11.99%
91004     city     Toronto  2022/1/28          -96.32%
91005     city      Tucson  2022/1/28           -13.8%
91006     city   Vancouver  2022/1/28          -28.98%
91007     city  Washington  2022/1/28          -51.92%

[91008 rows x 4 columns]

In [ ]:
# Check that Montreal is spelt correctly
df_unpivoted[df_unpivoted['Name'].str.contains('Montr')]

       Type      Name       date change_from_2019
104    city  MontrÃ©al  2020/2/18              16%
232    city  MontrÃ©al  2020/2/19              14%
360    city  MontrÃ©al  2020/2/20              -5%
488    city  MontrÃ©al  2020/2/21              -1%
616    city  MontrÃ©al  2020/2/22              14%
...     ...       ...        ...              ...
90472  city  MontrÃ©al  2022/1/24          -99.64%
90600  city  MontrÃ©al  2022/1/25          -99.44%
90728  city  MontrÃ©al  2022/1/26          -99.56%
90856  city  MontrÃ©al  2022/1/27          -99.44%
90984  city  MontrÃ©al  2022/1/28          -99.91%

[711 rows x 4 columns]

In [ ]:
df_unpivoted.to_csv('unpivoted-opentable-seated-diner-data.csv', encoding=encoding_type)

In [ ]:
files.download('unpivoted-opentable-seated-diner-data.csv')